# 単回帰分析練習

In [39]:
import pandas as pd 
import numpy as np
from sklearn import linear_model
from sklearn.externals import joblib


# 「x1が気温、x2がガチャの売り上げ。気温からガチャの売り上げを予測する」らしい

data = pd.read_csv("data.csv");print(data)

#  線形回帰モデル

clf = linear_model.LinearRegression()

# 説明変数xに"x1"のデータを使用
# 説明変数はn個の二次元配列で渡す必要がある
# x = data.loc[:, "x1"] じゃダメ。
x = data.loc[:,["x1"]].values;print(x)

# 目的変数yに"x2"のデータを使用
# 被説明変数は一次元配列で良い
y = data["x2"].values;print(y)

# 予測モデルを作成(単回帰)
clf.fit(x,y)

# パラメータ(回帰係数, 切片)を抽出
[b] = clf.coef_
a = clf.intercept_

# パラメータの表示
print("回帰係数",b)
print("切片:",a)
print("決定係数:",clf.score(x,y))

# 学習結果の出力
joblib.dump(clf,"./cfl.learn")

   x1    x2  x3
0  45  17.5  30
1  38  17.0  25
2  41  18.5  20
3  34  18.5  30
4  59  16.0  45
5  47  19.0  35
6  35  19.5  25
7  43  16.0  35
8  54  18.0  35
9  52  19.0  40
[[45]
 [38]
 [41]
 [34]
 [59]
 [47]
 [35]
 [43]
 [54]
 [52]]
[17.5 17.  18.5 18.5 16.  19.  19.5 16.  18.  19. ]
回帰係数 -0.049548095545513246
切片: 20.11975468043899
決定係数: 0.10943356354296774


['./cfl.learn']

In [35]:
# ここで登場した文法について

data
# loc, ilocで行の指定を:（全体のスライス）にすると列全体を参照できる。
d = data.loc[:, ["x1"]].values;
# つまりこれはx1列全体
# ["X1"]と包んでいるのは配列にしたいから？
# 配列にする必要があるのか？
d

array([[45],
       [38],
       [41],
       [34],
       [59],
       [47],
       [35],
       [43],
       [54],
       [52]])

# 重回帰分析

In [42]:
import pandas as pd 
import numpy as np
from sklearn import linear_model
from sklearn.externals import joblib


# 「景気動向指数」「若者の平均年収」から「ガチャの売り上げ」を予測する

data = pd.read_csv("data.csv")
clf = linear_model.LinearRegression()

# 説明変数にx1とx2を使用
X =data.loc[:, ["x1","x2"]].values;print(X)

# なるほど、重回帰分析前提で使うから一個体を一配列とみなさないといけないのだ


# 目的変数にx3のデータを使用

# 目的変数にx３のデータを使用
Y = data["x3"].values

# 予測モデルを作成
clf.fit(X,Y)

# 回帰係数と切片の抽出
a = clf.coef_
b = clf.intercept_


# 回帰係数
print("回帰係数: ", a)
print("切片：", b)
print("決定係数：", clf.score(X,Y))

# 回帰係数:  [ 0.70068905 -0.64667957]
# 切片： 12.184694815481183
# 決定係数： 0.6624246214760456

[[45.  17.5]
 [38.  17. ]
 [41.  18.5]
 [34.  18.5]
 [59.  16. ]
 [47.  19. ]
 [35.  19.5]
 [43.  16. ]
 [54.  18. ]
 [52.  19. ]]
回帰係数:  [ 0.70068905 -0.64667957]
切片： 12.184694815481183
決定係数： 0.6624246214760456
