In [9]:
x <-6

#

rm 削除
ls インスペクト

五則演算

paste("a","b","c")　文字列結合

データ型変換
as.character(x)
as.numeric()

## ベクトル

v<-c(1,2,3)
v[2]
v[2] <-10
x <-c(1,2,3)
y <-c(1,2,3)

x>y 
x+y

含む含まない
x  %in& y

和集合　union(x,y)
積集合 intersect(x,y)


## 因子ベクトル
x <- c("S","M","L","M","L")
x 

x.fc <- factor(x)
x.fc



In [12]:
paste("a","b","c",sep = "/")

[1] "a/b/c"

In [13]:

rm(x)
x

ERROR: Error in eval(expr, envir, enclos):  オブジェクト 'x' がありません 


In [22]:
x <- c("S","M","L","M","L")
x 

x.fc <- factor(x)
# x.fc
# levels(x.fc)
# レベルづけ

x.fc <- factor(x, levels=c("S","M","L"))
x.fc

# 順番付きレベルつけ

x.or <-ordered(x, levels=c("S","M","L"))
x.or

[1] "S" "M" "L" "M" "L"

[1] S M L M L
Levels: S M L

[1] S M L M L
Levels: S < M < L

In [26]:
# 行列
x <- matrix(1:6, nrow=3, ncol=2)
x

x <-matrix(1:6, nrow=3, ncol=2,byrow=TRUE)
x

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [28]:
x <-rbind(c(1,2), 3:4, 5:6)
x

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6

In [29]:
x<- cbind(c(1,2), 3:4, 5:6)
x

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [37]:
# 要素へのアクセス
x<- cbind(c(1,2), 3:4, 5:6)
# 1	3	5
# 2	4	6



x[,1]

x[2,]

x[1,2]

x[1,1:2]


x[1,c(1,2)]

x[1,c(1,3)]

# editはjupyterではサポートされていません

[1] 1 2

[1] 2 4 6

[1] 3

[1] 1 3

[1] 1 3

[1] 1 5

ERROR: Error in edit(x): ‘edit()’ not yet supported in the Jupyter R kernel


In [47]:
# リスト
# 別のデータ型のリストをまとめる

x <- list(5:10, "abc" , matrix(1:6, nrow=2, ncol =3))
x

x[1]

x[[1]]

x[[2]]

x[[3]]

x[[3]][1,2]

[[1]]
[1]  5  6  7  8  9 10

[[2]]
[1] "abc"

[[3]]
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

[[1]]
[1]  5  6  7  8  9 10

[1]  5  6  7  8  9 10

[1] "abc"

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

[1] 3

In [54]:
# データフレーム
x <- data.frame(SIZE=c("M", "L","S","L","M"), SALES=c(1,2,3,1,2))
x

x[1,1]
x$SIZE



SIZE SALES
1 M    1    
2 L    2    
3 S    3    
4 L    1    
5 M    2

[1] M
Levels: L M S

[1] M L S L M
Levels: L M S

In [ ]:
# データ集計
# # 
# sum()
# max()
# min()
# mean()
# median()
# summary()
# str()